// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:550277370430:web:728a97be0f57291aec776f',
    messagingSenderId: '550277370430',
    projectId: 'stranger-sync-c3d37',
    authDomain: 'stranger-sync-c3d37.firebaseapp.com',
    databaseURL: 'https://stranger-sync-c3d37-default-rtdb.firebaseio.com',
    storageBucket: 'stranger-sync-c3d37.firebasestorage.app',
    measurementId: 'G-L3BL6945S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:550277370430:android:eedf459ef910f21aec776f',
    messagingSenderId: '550277370430',
    projectId: 'stranger-sync-c3d37',
    databaseURL: 'https://stranger-sync-c3d37-default-rtdb.firebaseio.com',
    storageBucket: 'stranger-sync-c3d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:550277370430:ios:cfa1ab259b803206ec776f',
    messagingSenderId: '550277370430',
    projectId: 'stranger-sync-c3d37',
    databaseURL: 'https://stranger-sync-c3d37-default-rtdb.firebaseio.com',
    storageBucket: 'stranger-sync-c3d37.firebasestorage.app',
    iosBundleId: 'com.example.d1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    
    appId: '1:550277370430:ios:cfa1ab259b803206ec776f',
    messagingSenderId: '550277370430',
    projectId: 'stranger-sync-c3d37',
    databaseURL: 'https://stranger-sync-c3d37-default-rtdb.firebaseio.com',
    storageBucket: 'stranger-sync-c3d37.firebasestorage.app',
    iosBundleId: 'com.example.d1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: '1:550277370430:web:94c51bce85cf0aa4ec776f',
    messagingSenderId: '550277370430',
    projectId: 'stranger-sync-c3d37',
    authDomain: 'stranger-sync-c3d37.firebaseapp.com',
    databaseURL: 'https://stranger-sync-c3d37-default-rtdb.firebaseio.com',
    storageBucket: 'stranger-sync-c3d37.firebasestorage.app',
    measurementId: 'G-PHMPN24859',
  );
}
